loans/urls.py
from django.urls import path
from .views import create_contact, contact_list, contact_detail, create_transaction

app_name='loans'

urlpatterns = [
    path ('create_contact', create_contact, name='create_contact'),
    path ('contacts_list', contact_list, name='contacts_list'),
    path ('contact/<int:id>', contact_detail, name='contact_detail'),
    path ('transaction/<str:type>/', create_transaction, name='create_transaction'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path ('loans/', include('loans.urls')),
]

users/urls.py
from django.urls import path
from .views import home, signup, login_view, logout_view

app_name='users'

urlpatterns = [
    path ('', home, name='home'),
    path ('signup/', signup, name='signup'),
    path ('login/', login_view, name='login'),
    path ('logout/', logout_view, name='logout'),
]

loans/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Contact(models.Model):
    name = models.CharField(max_length=50)
    number = models.CharField (max_length=15)
    user = models.ForeignKey (User, on_delete=models.CASCADE)
    debit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    credit = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} ({self.number})' 

TRANSACTION_CHOICE = (
    ('borrow', 'Взять в долг'),
    ('repay', 'Погасить займ'),
    ('lend', 'Дать в долг'),
    ('receive', 'Принять погашение'),
)

class Transaction(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    transaction_type = models.CharField(
        max_length=20, choices=TRANSACTION_CHOICE, default='borrow',)

TELEGRAM_ACTION_CHOICE = (
    ('add_contact', 'Добавить контакт'),
    ('borrow', 'Взять в долг'),
    ('repay', 'Погасить займ'),
    ('lend', 'Дать в долг'),
    ('receive', 'Принять погашение'),
    ('register', 'Регистрация')
)

class TelegramMessageId(models.Model):
    chat_id = models.CharField(max_length=20)
    message_id = models.CharField(max_length=20)
    action = models.CharField (
        max_length=20, choices=TELEGRAM_ACTION_CHOICE, default='borrow')
    contact_id = models.IntegerField(blank=True, null=True)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    chat_id = models.CharField(max_length=20, blank=True, null=True)
    def __str__(self):
        return self.username

loans/forms.py
from django import forms
from .models import Contact, Transaction


class CreateContactForm(forms.ModelForm):
    class Meta:
     model = Contact
     fields = ('name', 'number')

class TransactionForm(forms.ModelForm):
   class Meta:
      model = Transaction
      exclude = ('created', 'transaction_type')

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    

loans/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import CreateContactForm, TransactionForm
from .models import Contact, TRANSACTION_CHOICE

def create_contact(request):
    if request.method == 'POST':
        form = CreateContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return redirect('loans:contacts_list')
    else:
        form = CreateContactForm ()
    return render (request, 'loans/create_contact.html', {'form':form})

@login_required
def contact_list (request):
    contacts = Contact.objects.filter(user=request.user)
    return render (request, 'loans/contacts_list.html', {'contacts': contacts})

@login_required
def contact_detail(request, id):
    contact = Contact.objects.get(id=id)
    return render(request, 'loans/contact_detail.html', {'contact':contact})

@login_required
def create_transaction(request, type):
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            transaction = form.save(commit=False)
            transaction.transaction_type = type
            contact = transaction.contact
            if type == 'borrow':
                contact.credit = contact.credit+transaction.amount
                contact.save()
                transaction.save ()
                return redirect('loans:contact_detail', id=contact.id)
            if type == 'repay':
                contact.credit = contact.credit-transaction.amount
                contact.save()
                transaction.save ()
                return redirect('loans:contact_detail', id=contact.id)
            if type == 'lend':
                contact.debit = contact.debit+transaction.amount
                contact.save()
                transaction.save ()
                return redirect('loans:contact_detail', id=contact.id)
            if type == 'receive':
                contact.debit = contact.debit-transaction.amount
                contact.save()
                transaction.save ()
                return redirect('loans:contact_detail', id=contact.id)
    form = TransactionForm()
    return render (request, 'loans/transaction.html', {'form':form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from .forms import UserForm

def home(request):
    return render(request, 'users/home.html')

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('users:home')
    else:
        form = UserForm()
    return render(request, 'users/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('users:home')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form':form})

def logout_view(request):
    logout(request)
    return redirect('users:home')

loans/templates/loans/contact_detail.html
{% extends 'base.html' %}

{% block content %}
<header class="blog-header py-3">
</header>
<div class="bg-light p-5 rounded">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="mb-4">Contact</h2>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">{{contact.name}}</h5>
              <h6 class="card-subtitle mb-2 text-body-secondary">{{contact.number}}</h6>
              <p class="card-text"> Debit: {{contact.debit}}</p>
              <p class="card-text"> Credit: {{contact.credit}}</p>
              <a href="#" class="card-link">Card link</a>
              <a href="#" class="card-link">Another link</a>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

loans/templates/loans/contacts_list.html
{% extends 'base.html' %}

{% block content %}
<header class="blog-header py-3">
</header>
<div class="bg-light p-5 rounded">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="mb-4">Contacts List</h2>
        {% for contact in contacts %}
             <div class="alert alert-info" role="alert">
              <a class="btn btn-dark" aria-current="page" href="{% url 'loans:contact_detail' id=contact.id %}">{{contact.name}} {{contact.number}}</a>
             </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

loans/templates/loans/create_contact.html
{% extends 'base.html' %}

{% block content %}
<header class="blog-header py-3">
</header>
<div class="bg-light p-5 rounded">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="mb-4">Create Contact</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

loans/templates/loans/transaction.html
{% extends 'base.html' %}

{% block content %}
<header class="blog-header py-3">
</header>
<div class="bg-light p-5 rounded">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="mb-4">Create Transaction</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Save</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

users/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Учет долгов{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

      <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{%url 'users:home' %}">My Cash</a></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'users:logout' %}">Выйти</a>
              </li>
              {%else%}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'users:signup' %}">Регистрация</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Войти</a>
              </li>
              {%endif%}
            </ul>
          </div>
        </div>
      </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <header class="blog-header py-3">
    </header>
</div>
  
  <main class="container">
    {% if request.user.is_authenticated %}

    <a class="btn btn-dark" aria-current="page" href="{% url 'loans:create_contact' %}">+ Add Contact</a>
    <a class="btn btn-dark" aria-current="page" href="{% url 'loans:contacts_list' %}">Contacts List</a>

    <div style="margin-top: 100px">
      <div class="row align-items-md-stretch">
        <div class="col-md-6">
          <div class="h-100 p-5 text-white bg-dark rounded-3">
            <h2>Взять  долг</h2>
            <p> </p>
            <a class="btn btn-outline-light" href="{% url 'loans:create_contact' %}">Взять</a>
            <a class="btn btn-outline-light" href="{% url 'loans:create_transaction' type='borrow' %}">Взять у контакта</a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="h-100 p-5 bg-light border rounded-3">
            <h2>Погасить долг</h2>
            <p></p>
            <a class="btn btn-outline-secondary" href="{% url 'loans:create_transaction' type='repay' %}">Погасить долг</a>
          </div>
        </div>
      </div>
  </div>
  
  <div style="margin-top: 100px">
      <div class="row align-items-md-stretch">
        <div class="col-md-6">
          <div class="h-100 p-5 text-white bg-dark rounded-3">
            <h2>Дать  в долг</h2>
            <p></p>
            <a class="btn btn-outline-light" href="{% url 'loans:create_contact' %}">Дать</a>
            <a class="btn btn-outline-light" href="{% url 'loans:create_transaction' type='lend' %}">Дать контакту</a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="h-100 p-5 bg-light border rounded-3">
            <h2>Получить погашение</h2>
            <p></p>
            <a class="btn btn-outline-secondary" href="{% url 'loans:create_transaction' type='receive' %}">Получить погашение</a>
          </div>
        </div>
      </div>
  </div>
  
  
      <footer class="pt-3 mt-4 text-muted border-top">
        © 2023
      </footer>
    </div>

    {%else%}
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
      <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">На нашем сайте вы сможете управлять своими долгами</h1>
      </div>
    </div>
    {%endif%}
  </main>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<header class="blog-header py-3">
</header>
<div class="bg-light p-5 rounded">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="mb-4">Log in</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Log in</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<header class="blog-header py-3">
</header>
<div class="bg-light p-5 rounded">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="mb-4">Sign up</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}